/*
 * This source file was generated by the Gradle 'init' task
 */
package org.APCSLowell;

public class GoogleBillboard {
    public boolean isPrime(long n) {
        for (int i = 2; i < Math.sqrt(dNum); i++){
            if (dNum%i == 0){
                return false;
            }
        }
        return dNum > 1;
    }
    public long firstPrimeNumberIn(String n) {
        // Write your code here.
        return -1;
    }
}
